### ISSUE TITLE
Dice roll Program

### ISSUE THREAD

**Issue by paperboy221** [germanoa/compiladores#2]
<img width="960" alt="assignment3" src="https://user-images.githubusercontent.com/28881889/30298036-e703553c-9717-11e7-8aa2-141a8960aad5.png">

I'm trying to print a new random number for each iteration(10) of the for loop, but it seems what I've done is repeat the same random number 10 times. Can someone help?

This is created in the C programming language.

**Comment by ZyriabDsgn** [comment]
Fetch rand with a different number everytime it is called. (Check out the POSIX Hour)
